# .github/workflows/verify-translations.yml
name: verify-translations
on:
  pull_request:
    branches: [ main ]
    paths:
      - 'app/translations/**.po'

jobs:
  compile:
    runs-on: blacksmith-2vcpu-ubuntu-2404
    steps:
      - uses: actions/checkout@v6
      - name: Compile .mo
        run: |
          pipx run babel pybabel compile -d app/translations
